version: '3.5'

services:
  backend:
    build: ./backend
    image: tornermarton/sheep-n-wolf
    container_name: sheep-n-wolf-be
    ports:
      - "3000:3000"
  frontend:
    image: nginx
    container_name: sheep-n-wolf-fe
    depends_on:
      - backend
    tty: true
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
